### ISSUE TITLE
UI does not refresh properly

### ISSUE THREAD

**Issue by Ziflin** [genielabs/HomeGenie-Android#4]
When turning a light On/Off and backing out/dismissing the popup dialog, the UI for that light in the list of devices is not refreshed so it displays the old state.

Also, if HomeGenie has been started and then switched out of (home button), if devices are manually changed and HomeGenie is restarted or switched back to, the state of those devices in the list is not updated.  There should either be a refresh button, or ideally HomeGenie would refresh when it is re-activated.

**Comment by bkenobi** [comment]
If you swipe to a different page, the state (icon) will update.  However, the info under the icon is not updated.

**Comment by genielabs** [comment]
I tried going to the home screen, did wait for 10 minutes or so, then went back to HG client but the status wa correctly updated.
Which version of the client is having this issue?

**Comment by bkenobi** [comment]
I'm running 1.0.15.  If I control a module from the Android app the icon does not update unless I switch tabs and then come back.  As I recall, it does not update the time below the icon.  If I control from the web interface while the Android app is open, it doesn't update as all.  I can exit the app and then come back (forcing a refresh) and it displays correctly in both cases.

I can't test at the moment because currently the app is blank.  I'll update to 1.0.16 and test again when it becomes available.

**Comment by Kejszijo** [comment]
Hi!

I found a reason, why not updated status in android app. When notification appears at the bottom, the switches status not refresh any more.
I close android app, and open again (the notification pop up desappear), the switch status refresh, until the notification not appear again.

I made a video:
https://drive.google.com/open?id=0B29zq2qZ6UHhd1JyeTJwMHI2NTE2VERYSVZGeUJJQW5nVXVR
